### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tacruc**
Add Specifications about the format

### CODE REVIEW

**Comment by icewind1991** [comment]
The leading `*` shouldn't be needed since the app already [adds `*`'s](https://github.com/icewind1991/files_snapshots/blob/master/lib/Snapshot.php#L79) around the data format

**Comment by tacruc** [comment]
Thanks, I have seen this, but somehow it fixes it for me and in Issue #6 it did the work two. But to be honest I have no Idea why.

If you want I can remove this commend, but I think the link to the PHP documentation is helpfull.

**Comment by tacruc** [comment]
OK I could contruct a case where the leading * did the trick but I don't know why.

```
<?php
$date = date_create_from_format('**d-M-Y*', '..15-Feb-2009*');
echo date_format($date, 'Y-m-d');

$date = date_create_from_format('*d-M-Y*', '..15-Feb-2009*');
echo date_format($date, 'Y-m-d');
?> 
```


Result:
```
2009-02-15
<b>Warning</b>: date_format() expects parameter 1 to be DateTimeInterface, boolean given in <b>[...][...]</b> on line <b>5</b>
```
**EDIT**
Figured out why it is needed:
Each * will only match until the next separator or digit, as it seems .- are separators and _ is not.

**Review by icewind1991 — APPROVED** [review]

**Comment by icewind1991** [comment]
Thanks for taking the time to debug

**Pull request merged**
